// =====================================
// Common error codes
// =====================================
const codeSenderAddressInvalid: Int = 1000;
const codeInflowValueNotSufficient: Int = 1001;
const codeBalanceNotSufficient: Int = 1002;
const codeUnauthorized: Int = 1003;
const codeNonceInvalid: Int = 1004;
const codeNotImplemented: Int = 1005;
const codeMsgValueInvalid: Int = 1006;
const codeForwardPayloadInvalid: Int = 1007;
