// =====================================
// Common error codes
// =====================================
const codeSenderAddressInvalid: Int = 50000;
const codeInflowValueNotSufficient: Int = 50001;
const codeBalanceNotSufficient: Int = 50002;
const codeUnauthorized: Int = 50003;
const codeNonceInvalid: Int = 50004;
const codeNotImplemented: Int = 50005;
const codeMsgValueInvalid: Int = 50006;
const codeForwardPayloadInvalid: Int = 50007;
