import "../common/errcodes.tact";

// =====================================
// Project specific error codes
// =====================================
const codeNotMintable: Int = 2000;
const codeExceedsMaxSupply: Int = 2001;
const codeMapIndexNotExists: Int = 2002;
const codeJettonBalanceInsufficient: Int = 2003;
const codeAmountShouldBePositive: Int = 2004;
const codeReceiverInsufficientReceiverTonAmount: Int = 2005;
