import "../common/errcodes.tact";

// =====================================
// Project specific error codes
// =====================================
const codeNotMintable: Int = 50100;
const codeExceedsMaxSupply: Int = 50101;
const codeMapIndexNotExists: Int = 50102;
const codeJettonBalanceInsufficient: Int = 50103;
const codeAmountShouldBePositive: Int = 50104;
const codeReceiverInsufficientReceiverTonAmount: Int = 50105;
