name: Test

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Node.js modules
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install -g yarn@1.22.22 && yarn install --frozen-lockfile

    - name: ./node_modules/.bin/blueprint build HelloWorld
      run: ./node_modules/.bin/blueprint build HelloWorld

    - name: ./node_modules/.bin/blueprint build Sample
      run: ./node_modules/.bin/blueprint build Sample

    - name: Run tests
      run: make test
